color: "#4f46e5"
copyright: "Copyright &copy; 2022 Acme Corp. All Rights Reserved"
footer:
  - title: About
    content: >
      Acme coorporation is the world's leading manufacturer of digital shapes.
      the shape lorem ipsum the shape lorem ipsum
      the shape lorem ipsum the shape lorem ipsum
      the shape lorem ipsum the shape lorem ipsum
  - title: Recent Blog Post
    recents: blog
    recentCount: 7
  - title: Contact Us 
    contact: true
style: blue
logo: /image/logo.png
logo_small: /image/logo.png
about_us: >
  Acme coorporation is the world's leading manufacturer of digital shapes.
  the shape lorem ipsum the shape lorem ipsum
  the shape lorem ipsum the shape lorem ipsum
  the shape lorem ipsum the shape lorem ipsum
recent_posts:
  enable: true